apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vagas-api
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels: { app: vagas-api }
  namespaceSelector:
    matchNames: ["demo"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s