apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-bridge
  namespace: monitoring
  labels: { app: alert-bridge }
spec:
  replicas: 1
  selector:
    matchLabels: { app: alert-bridge }
  template:
    metadata:
      labels: { app: alert-bridge }
    spec:
      containers:
        - name: alert-bridge
          image: alert-bridge:dev
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: GCHAT_WEBHOOK_URL
              value: "WEBHOOK_URL_GCHAT_AQUI"
            - name: DISCORD_WEBHOOK_URL
              value: "WEBHOOK_URL_DISCORD_AQUI"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-bridge
  namespace: monitoring
  labels: { app: alert-bridge }
spec:
  selector: { app: alert-bridge }
  ports: [{ port: 8080, targetPort: 8080 }]
